import type { NextPage } from "next"
import Head from "next/head"
import Footer from "../components/Footer/Footer"
import Header from "../components/Header/Header"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Footer />
    </>
  )
}

export default Home
